"use client";

/**
 * 지역별 폐기물 발생과 처리 비교 — Figma 125:5148.
 *
 * A scatter of two SERVED per-resident indicators, one per region:
 *   X — official per-capita waste generation for one stream (RCIS reporting geography)
 *   Y — the derived per-capita facility throughput (지역 내 시설 / 인근 5km 시설)
 *
 * Everything analytical lives in `lib/landfillScatter.ts`: this file positions dots
 * and prints the strings that module returns. NO distance, buffer, intersection, or
 * aggregate is computed here — the 인근 5km measure is a backend indicator with a
 * served buffer distance, not a browser-side geometry pass.
 *
 * ── Why the two axes are labelled as different bases, loudly ──────────────────
 * The Y value is measured at the facility's LOCATION; the X value is measured at the
 * point of GENERATION. Their difference is not a processing deficit and the platform
 * says so in `SCATTER_COMPARABILITY_CAVEAT`, which is rendered unconditionally with
 * the plot rather than hidden in a disclosure — it is the one sentence that stops the
 * quadrant labels being read as a verdict on a region.
 *
 * ── Accessibility ─────────────────────────────────────────────────────────────
 * Every dot is a real <button> in a documented tab order, so selection works from the
 * keyboard and each point's exact served values are reachable as text. The dots are
 * NOT the only representation: the full list is available as a table below, because a
 * <title> tooltip is unreachable by touch and by screen readers.
 */

import { useId, useMemo, useState } from "react";

import type { FacilityBurdenEnvelope, ReportingPerCapitaEnvelope } from "../../lib/api";
import type { BurdenMode, ScatterDataset, ScatterPoint } from "../../lib/landfillScatter";
import {
  buildScatterDataset,
  QUADRANT_LABELS,
  quadrantOf,
  SCATTER_COMPARABILITY_CAVEAT,
  SCATTER_EXCLUSION_LABELS,
  SCATTER_SCOPE_ORDER,
  scatterScopeColor,
  scatterScopeLabel,
  scopeCounts,
} from "../../lib/landfillScatter";
import { formatQuantity } from "../../lib/metrics";
import Accordion from "../ui/Accordion";
import DataStatusBadge from "../ui/DataStatusBadge";
import Dialog from "../ui/Dialog";
import SectionCard from "../ui/SectionCard";
import SegmentedControl from "../ui/SegmentedControl";
import { PAGE2_CARD_CLASS } from "./shared";

/**
 * The X-axis stream. `HOUSEHOLD` — 생활(가정) 폐기물 — is the one series whose
 * per-resident value a resident can interpret about themselves; the business and
 * construction streams are generated by sites, not households, and their per-capita
 * form carries a standing caveat (lib/metrics.ts NON_RESIDENTIAL_CAVEAT). This
 * comparison therefore fixes the stream rather than offering a picker that would
 * silently change what "1인당" means.
 */
const SCATTER_WASTE_STREAM = "HOUSEHOLD";
const SCATTER_STREAM_LABEL = "생활계 폐기물";

const MODE_OPTIONS = [
  { key: "located" as const, label: "지역 내 시설", testId: "landfill-scatter-mode-located" },
  { key: "buffer" as const, label: "인근 5km 시설", testId: "landfill-scatter-mode-buffer" },
];

export interface LandfillGenerationScatterProps {
  perCapita: ReportingPerCapitaEnvelope | null;
  burden: FacilityBurdenEnvelope | null;
}

export default function LandfillGenerationScatter({
  perCapita,
  burden,
}: LandfillGenerationScatterProps) {
  const [mode, setMode] = useState<BurdenMode>("located");
  const [selected, setSelected] = useState<string | null>(null);
  // 표로 보기 (기술요청 #16) — presentation state only.
  const [tableOpen, setTableOpen] = useState(false);

  const dataset = useMemo(
    () => buildScatterDataset(perCapita, burden, SCATTER_WASTE_STREAM, mode),
    [perCapita, burden, mode],
  );
  const selectedPoint = dataset.points.find((point) => point.regionCode === selected) ?? null;

  return (
    <SectionCard
      title="지역별 폐기물 발생과 처리 비교"
      description={`폐기물 발생 수준(가로축)과 시설 처리 수준(세로축)을 비교합니다 · ${SCATTER_STREAM_LABEL} 기준`}
      headerAside={
        <SegmentedControl
          options={MODE_OPTIONS}
          value={mode}
          onChange={(next) => {
            setMode(next);
            // The selection is kept: the same region exists in both modes, and
            // dropping it would make the toggle feel like it reset the view.
          }}
          ariaLabel="시설 처리 수준의 집계 범위"
          testId="landfill-scatter-mode"
        />
      }
      className={PAGE2_CARD_CLASS}
      testId="landfill-scatter"
    >
      {dataset.points.length === 0 ? (
        <p className="text-xs text-ink-subtle" data-testid="landfill-scatter-empty">
          두 지표를 같은 지역 단위로 맞출 수 있는 자료가 없어 비교를 표시하지 않습니다.
        </p>
      ) : (
        <>
          <ScopeLegend dataset={dataset} />
          <ScatterPlot
            dataset={dataset}
            selected={selected}
            onSelect={(code) => setSelected((current) => (current === code ? null : code))}
          />
          <p
            className="mt-2 text-xs leading-relaxed text-warn"
            data-testid="landfill-scatter-caveat"
          >
            {SCATTER_COMPARABILITY_CAVEAT}
          </p>
          {/* The "클릭하거나 키보드로 선택하면 …" instruction is NOT repeated here. The
              detail slot immediately below is empty until a point is chosen, and its
              empty state IS that instruction — printing it twice, one line apart,
              was the same sentence saying the same thing to the same reader. */}

          <SelectedPointDetail point={selectedPoint} dataset={dataset} />

          <div className="mt-3 flex flex-col gap-2">
            {/* 기술요청 #16 — '표로 보기' is a popup, on the shared `ui/Dialog`. */}
            <button
              type="button"
              className="wep-btn-quiet w-full justify-between"
              onClick={() => setTableOpen(true)}
              data-testid="landfill-scatter-exact"
            >
              표로 보기 (지역별 정확한 값)
            </button>
            <Dialog
              open={tableOpen}
              title="지역별 정확한 값"
              description={`1인당 ${SCATTER_STREAM_LABEL} 발생량과 1인당 시설 처리량 · ${dataset.points.length}개 시·군·구`}
              onClose={() => setTableOpen(false)}
              testId="landfill-scatter-table-modal"
            >
              <div className="px-5 py-4">
                <ScatterTable dataset={dataset} />
                <div className="mt-4 flex justify-end border-t border-hairline pt-3">
                  <button
                    type="button"
                    className="wep-btn-primary"
                    onClick={() => setTableOpen(false)}
                    data-testid="landfill-scatter-table-dismiss"
                  >
                    닫기
                  </button>
                </div>
              </div>
            </Dialog>
            {/* KEPT as an inline disclosure, deliberately — see the note in the
                dashboard: this is the ONLY place the excluded regions are named with
                their reason, and 기술요청 #15 asks for it to be deleted. Deleting it
                would turn a disclosed exclusion into a silent one. */}
            <Accordion label="자료 기준과 비교에서 빠진 지역" testId="landfill-scatter-coverage">
              <ScatterCoverage dataset={dataset} mode={mode} />
            </Accordion>
          </div>
        </>
      )}
    </SectionCard>
  );
}

/**
 * The 시·도 grouping key, stated in text beside the plot.
 *
 * This exists so COLOUR IS NOT THE ONLY CARRIER of the grouping (WCAG 1.4.1). It is
 * also the visible proof of the page's data contract: it prints each 시·도's dot
 * COUNT, so "서울특별시 25곳 · 인천광역시 10곳 · 경기도 24곳" reads as 59 municipalities
 * in three groups — not as three 시·도 observations. A regression that collapsed the
 * plot to one dot per 시·도 would show up here as "1곳" three times.
 *
 * Groups with no plotted dot are omitted rather than shown as 0곳: an empty group is
 * not a measurement, and the 빠진 지역 disclosure below already names what dropped out
 * and why.
 */
function ScopeLegend({ dataset }: { dataset: ScatterDataset }) {
  const counts = scopeCounts(dataset.points);
  const groups = [
    ...SCATTER_SCOPE_ORDER.filter((scope) => (counts.get(scope) ?? 0) > 0),
    ...((counts.get(null) ?? 0) > 0 ? [null] : []),
  ];
  if (groups.length === 0) return null;
  return (
    <ul
      className="mb-1 flex flex-wrap items-center gap-x-4 gap-y-1 text-[11px] text-ink-muted"
      data-testid="landfill-scatter-legend"
    >
      {groups.map((scope) => (
        <li key={scope ?? "none"} className="flex items-center gap-1.5">
          <span
            aria-hidden
            className="inline-block h-2.5 w-2.5 flex-none rounded-full"
            style={{ backgroundColor: scatterScopeColor(scope) }}
            data-testid="landfill-scatter-legend-swatch"
            data-scope={scope ?? "none"}
          />
          <span>
            {scatterScopeLabel(scope)}{" "}
            <span className="tabular-nums text-ink-subtle">{counts.get(scope) ?? 0}곳</span>
          </span>
        </li>
      ))}
      <li className="text-ink-subtle">점 하나 = 시·군·구 한 곳</li>
    </ul>
  );
}

const PLOT = { width: 660, height: 340, padLeft: 62, padBottom: 30, padTop: 12, padRight: 14 };
/** Where the axis ticks sit, as fractions of each axis's served maximum. */
const AXIS_FRACTIONS = [0, 0.25, 0.5, 0.75, 1] as const;

/**
 * A tick label for the axis SCALE.
 *
 * Rounded to whole kg, unlike every VALUE on this screen. That is safe here and only
 * here: a tick is a position on a ruler, not a served measurement — it is derived from
 * the axis maximum times a fraction, it is `aria-hidden`, and no region's figure is
 * ever read from it. The exact per-region values stay the point buttons' own labels and
 * the 표로 보기 table, both of which print the served string unrounded.
 */
function axisTick(value: number): string {
  return Math.round(value).toLocaleString("en-US");
}

/**
 * The plot itself.
 *
 * Positions are scaled to the maximum value ON SCREEN, which is a layout decision and
 * never reconstructs a displayed figure — every number a reader sees is the served
 * string, formatted. The quadrant lines are the medians of the plotted points, and
 * they are labelled as such: they are a reading aid for this set of regions, not a
 * target, a threshold, or a national reference.
 */
function ScatterPlot({
  dataset,
  selected,
  onSelect,
}: {
  dataset: ScatterDataset;
  selected: string | null;
  onSelect: (code: string) => void;
}) {
  const titleId = useId();
  const maxX = Math.max(...dataset.points.map((point) => point.generation), 1);
  const maxY = Math.max(...dataset.points.map((point) => point.burden), 1);
  const plotWidth = PLOT.width - PLOT.padLeft - PLOT.padRight;
  const plotHeight = PLOT.height - PLOT.padTop - PLOT.padBottom;
  const x = (value: number) => PLOT.padLeft + (value / maxX) * plotWidth;
  const y = (value: number) => PLOT.padTop + plotHeight - (value / maxY) * plotHeight;

  return (
    <div className="overflow-x-auto">
      <svg
        viewBox={`0 0 ${PLOT.width} ${PLOT.height}`}
        className="h-[20rem] w-full min-w-[34rem]"
        role="group"
        aria-labelledby={titleId}
        data-testid="landfill-scatter-plot"
      >
        <title id={titleId}>
          {`가로축 1인당 ${SCATTER_STREAM_LABEL} 발생량, 세로축 1인당 시설 처리량. ${dataset.points.length}개 지역.`}
        </title>

        {/* Axes */}
        <line
          x1={PLOT.padLeft}
          y1={PLOT.padTop}
          x2={PLOT.padLeft}
          y2={PLOT.padTop + plotHeight}
          stroke="#c8cad6"
        />
        <line
          x1={PLOT.padLeft}
          y1={PLOT.padTop + plotHeight}
          x2={PLOT.padLeft + plotWidth}
          y2={PLOT.padTop + plotHeight}
          stroke="#c8cad6"
        />

        {/* Median reference lines. Drawn only when the medians exist (two or more
            points); below that no quadrant claim is made at all. */}
        {dataset.generationMedian !== null && (
          <line
            x1={x(dataset.generationMedian)}
            y1={PLOT.padTop}
            x2={x(dataset.generationMedian)}
            y2={PLOT.padTop + plotHeight}
            stroke="#a0a4b8"
            strokeDasharray="4 4"
            data-testid="landfill-scatter-median-x"
          />
        )}
        {dataset.burdenMedian !== null && (
          <line
            x1={PLOT.padLeft}
            y1={y(dataset.burdenMedian)}
            x2={PLOT.padLeft + plotWidth}
            y2={y(dataset.burdenMedian)}
            stroke="#a0a4b8"
            strokeDasharray="4 4"
            data-testid="landfill-scatter-median-y"
          />
        )}

        {/* Axis ticks. The Figma frame (125:5162) draws a scaled plot, not a bare
            box: without numbers on the axes a reader can see that one region sits
            further right than another but not by how much, which is most of what a
            scatter is for. Five evenly-spaced ticks per axis, each printed from the
            same formatter the readout uses, so a tick and a point can never disagree.
            Decorative for assistive tech — the exact per-region values are the point
            buttons' own labels and the 표로 보기 table. */}
        {AXIS_FRACTIONS.map((fraction) => {
          const tickX = PLOT.padLeft + fraction * plotWidth;
          const tickY = PLOT.padTop + plotHeight - fraction * plotHeight;
          return (
            <g key={fraction} aria-hidden>
              {/* A horizontal guide at each y tick, behind the points. */}
              {fraction > 0 && (
                <line
                  x1={PLOT.padLeft}
                  y1={tickY}
                  x2={PLOT.padLeft + plotWidth}
                  y2={tickY}
                  stroke="#eff0f6"
                />
              )}
              <text
                x={PLOT.padLeft - 5}
                y={tickY + 3}
                textAnchor="end"
                className="fill-ink-subtle text-[9px]"
                data-testid="landfill-scatter-tick-y"
              >
                {axisTick(maxY * fraction)}
              </text>
              <text
                x={tickX}
                y={PLOT.padTop + plotHeight + 12}
                textAnchor="middle"
                className="fill-ink-subtle text-[9px]"
                data-testid="landfill-scatter-tick-x"
              >
                {axisTick(maxX * fraction)}
              </text>
            </g>
          );
        })}

        {/* The four quadrant callouts the frame places in the corners. They name where
            the MEDIAN LINES fall, never a verdict on a region: the wording is the same
            `QUADRANT_LABELS` vocabulary the selected-point readout uses, which says
            중앙값 이상 / 미만 rather than 높음 / 낮음, and the readout still appends
            "(순위나 평가가 아닙니다)". Drawn only when both medians exist — with fewer
            than two points there are no quadrants to name. */}
        {dataset.generationMedian !== null && dataset.burdenMedian !== null && (
          <g aria-hidden data-testid="landfill-scatter-quadrant-labels">
            <text x={PLOT.padLeft + 6} y={PLOT.padTop + 11} className="fill-ink-faint text-[9px]">
              {QUADRANT_LABELS["high-burden"]}
            </text>
            <text
              x={PLOT.padLeft + plotWidth - 4}
              y={PLOT.padTop + 11}
              textAnchor="end"
              className="fill-ink-faint text-[9px]"
            >
              {QUADRANT_LABELS["high-high"]}
            </text>
            <text
              x={PLOT.padLeft + 6}
              y={PLOT.padTop + plotHeight - 6}
              className="fill-ink-faint text-[9px]"
            >
              {QUADRANT_LABELS["low-low"]}
            </text>
            <text
              x={PLOT.padLeft + plotWidth - 4}
              y={PLOT.padTop + plotHeight - 6}
              textAnchor="end"
              className="fill-ink-faint text-[9px]"
            >
              {QUADRANT_LABELS["high-generation"]}
            </text>
          </g>
        )}

        {/* ── Pass 1: every dot ─────────────────────────────────────────────────
            One circle per 시·군·구, filled by its parent 시·도 (기술요청 #14). The
            grain is the contract: this map runs over `dataset.points`, which is one
            entry per municipality, and NOTHING here groups or aggregates them — the
            시·도 only chooses a fill.

            Selection emphasis follows annotation 271:428 (색 진하게 + 정확한 지역명):
            the chosen dot KEEPS its 시·도 colour and gains size and a ring, while the
            rest drop to a third of their opacity. Repainting the selection navy — as
            it was — threw away the one attribute the reader had just been asked to
            read the plot by. */}
        {dataset.points.map((point) => {
          const isSelected = point.regionCode === selected;
          const dimmed = selected !== null && !isSelected;
          return (
            /* A real button: focusable, activatable by Enter/Space, and announced with
               its 시·도 and its exact values. SVG <circle> alone is none of those. */
            <circle
              key={point.regionCode}
              role="button"
              tabIndex={0}
              aria-pressed={isSelected}
              aria-label={`${point.regionName}, ${scatterScopeLabel(point.scope)} — 1인당 발생량 ${formatQuantity(point.generationExact)} kg, 1인당 시설 처리량 ${formatQuantity(point.burdenExact)} kg`}
              cx={x(point.generation)}
              cy={y(point.burden)}
              r={isSelected ? 7.5 : 4.5}
              fill={scatterScopeColor(point.scope)}
              fillOpacity={dimmed ? 0.32 : 1}
              stroke={isSelected ? "#111a56" : "none"}
              strokeWidth={isSelected ? 2.5 : 0}
              className="cursor-pointer focus:outline-none focus-visible:stroke-[#111a56] focus-visible:stroke-2"
              data-testid="landfill-scatter-point"
              data-region={point.regionCode}
              data-scope={point.scope ?? "none"}
              data-selected={isSelected ? "true" : undefined}
              onClick={() => onSelect(point.regionCode)}
              onKeyDown={(event) => {
                if (event.key === "Enter" || event.key === " ") {
                  event.preventDefault();
                  onSelect(point.regionCode);
                }
              }}
            />
          );
        })}

        {/* ── Pass 2: the selected dot's label, ON TOP ──────────────────────────
            기술요청 #17: the label used to be drawn inside the same <g> as its own
            circle, so every dot painted AFTER it covered it — at 59 points a label
            near the middle of the cloud was routinely half-hidden behind later dots.
            Painting all labels in a second pass puts them above every circle, which
            is what "맨 앞으로" asks for.

            A pale halo behind the text keeps it legible where it crosses a dense
            cluster; it is `aria-hidden` decoration, and the name itself is also in
            the readout below the plot, so nothing depends on reading it here. */}
        {(() => {
          const point = dataset.points.find((candidate) => candidate.regionCode === selected);
          if (!point) return null;
          const label = point.regionName;
          const anchorX = x(point.generation);
          const anchorY = y(point.burden);
          // Flip the label inside the plot when the dot sits near the right edge, so
          // a right-hand region's name is never clipped by the card.
          const flip = anchorX > PLOT.padLeft + (PLOT.width - PLOT.padLeft - PLOT.padRight) * 0.72;
          return (
            <g data-testid="landfill-scatter-point-label-group">
              <text
                x={flip ? anchorX - 11 : anchorX + 11}
                y={anchorY - 9}
                textAnchor={flip ? "end" : "start"}
                aria-hidden
                stroke="#ffffff"
                strokeWidth={3.5}
                strokeLinejoin="round"
                className="text-[10px] font-bold"
              >
                {label}
              </text>
              <text
                x={flip ? anchorX - 11 : anchorX + 11}
                y={anchorY - 9}
                textAnchor={flip ? "end" : "start"}
                className="fill-ink text-[10px] font-bold"
                data-testid="landfill-scatter-point-label"
              >
                {label}
              </text>
            </g>
          );
        })()}

        <text
          x={PLOT.padLeft + plotWidth / 2}
          y={PLOT.height - 4}
          textAnchor="middle"
          className="fill-ink-subtle text-[10px]"
        >
          1인당 {SCATTER_STREAM_LABEL} 발생량 (kg/인·년) · 발생지 기준
        </text>
        <text
          x={12}
          y={PLOT.padTop + plotHeight / 2}
          textAnchor="middle"
          transform={`rotate(-90 12 ${PLOT.padTop + plotHeight / 2})`}
          className="fill-ink-subtle text-[10px]"
        >
          1인당 시설 처리량 (kg/인·년) · 시설 소재지 기준
        </text>
      </svg>
    </div>
  );
}

/** The selected region's exact served values — the plot's text counterpart. */
function SelectedPointDetail({
  point,
  dataset,
}: {
  point: ScatterPoint | null;
  dataset: ScatterDataset;
}) {
  if (!point) {
    return (
      // KEPT. It reads like a duplicate of the card footer, but it is the empty
      // state of the detail slot rather than standing orientation: it reserves the
      // slot's height so selecting a point does not shift the chart, and
      // LandfillGenerationScatter.test.tsx contracts it as the proof that pressing a
      // selected point CLEARS the selection instead of trapping the reader in it.
      <p
        className="mt-2 rounded-card border border-hairline bg-surface-muted p-3 text-xs text-ink-subtle"
        data-testid="landfill-scatter-selection"
      >
        {/* The Figma frame's own footnote (125:5217 / annotation 271:429), verbatim —
            "· 점을 클릭하면 해당 지역을 강조하고 상세 정보를 확인할 수 있습니다." — with
            the keyboard affordance appended. The keyboard clause is NOT decoration:
            the dots are operable by Enter/Space and dropping it would leave that
            undiscoverable. */}
        점을 클릭하면 해당 지역을 강조하고 상세 정보를 확인할 수 있습니다. (키보드로도 선택할 수 있습니다)
      </p>
    );
  }
  const quadrant = quadrantOf(point, dataset);
  return (
    <div
      className="mt-2 rounded-card border border-hairline bg-surface-muted p-3"
      data-testid="landfill-scatter-selection"
    >
      {/* Announced on selection so a screen-reader user hears the values the sighted
          reader just revealed. */}
      <p role="status" className="sr-only">
        {point.regionName} 선택됨.
      </p>
      <p className="flex items-center gap-1.5 text-sm font-bold text-ink">
        <span
          aria-hidden
          className="inline-block h-2.5 w-2.5 flex-none rounded-full"
          style={{ backgroundColor: scatterScopeColor(point.scope) }}
        />
        {point.regionName}
        <span
          className="text-[11px] font-normal text-ink-subtle"
          data-testid="landfill-scatter-selection-scope"
        >
          {scatterScopeLabel(point.scope)}
        </span>
      </p>
      <dl className="mt-1 grid grid-cols-1 gap-x-4 gap-y-1 text-xs sm:grid-cols-2">
        <div>
          <dt className="inline text-ink-subtle">1인당 발생량 </dt>
          <dd className="inline font-medium tabular-nums text-ink">
            {formatQuantity(point.generationExact)} kg/인·년
          </dd>
        </div>
        <div>
          <dt className="inline text-ink-subtle">1인당 시설 처리량 </dt>
          <dd className="inline font-medium tabular-nums text-ink">
            {formatQuantity(point.burdenExact)} kg/인·년
          </dd>
        </div>
        <div>
          <dt className="inline text-ink-subtle">집계된 시설 </dt>
          <dd className="inline font-medium tabular-nums text-ink">{point.facilityCount}개</dd>
        </div>
        <div>
          <dt className="inline text-ink-subtle">인구 </dt>
          <dd className="inline font-medium tabular-nums text-ink">
            {point.population.toLocaleString("en-US")}명
          </dd>
        </div>
      </dl>
      {quadrant && (
        <p className="mt-1 text-[11px] text-ink-subtle" data-testid="landfill-scatter-quadrant">
          표시된 지역들의 중앙값 기준: {QUADRANT_LABELS[quadrant]} (순위나 평가가 아닙니다)
        </p>
      )}
      {point.burdenIsPartial && (
        <p className="mt-1 text-[11px] text-warn" data-testid="landfill-scatter-partial">
          일부 시설의 처리량이 보고되지 않아 이 지역의 처리량은 과소집계입니다.
        </p>
      )}
    </div>
  );
}

/** Every plotted region's exact served values, as text. */
function ScatterTable({ dataset }: { dataset: ScatterDataset }) {
  return (
    <div>
      <table className="w-full text-left text-sm" data-testid="landfill-scatter-table">
        <caption className="sr-only">지역별 1인당 발생량과 1인당 시설 처리량</caption>
        <thead>
          <tr className="text-ink-subtle">
            <th scope="col" className="py-0.5 pr-3 font-medium">
              지역
            </th>
            {/* The grouping key as TEXT. Together with the legend this is what keeps
                the 시·도 encoding readable without colour vision (기술요청 #14). */}
            <th scope="col" className="py-0.5 pr-3 font-medium">
              시·도
            </th>
            <th scope="col" className="py-0.5 pr-3 text-right font-medium">
              1인당 발생량 (kg/인·년)
            </th>
            <th scope="col" className="py-0.5 text-right font-medium">
              1인당 시설 처리량 (kg/인·년)
            </th>
          </tr>
        </thead>
        <tbody>
          {dataset.points.map((point) => (
            <tr key={point.regionCode}>
              <th scope="row" className="py-0.5 pr-3 font-normal text-ink-muted">
                {point.regionName}
              </th>
              <td className="py-0.5 pr-3 text-ink-muted" data-testid="landfill-scatter-table-scope">
                {scatterScopeLabel(point.scope)}
              </td>
              <td className="py-0.5 pr-3 text-right tabular-nums text-ink-muted">
                {formatQuantity(point.generationExact)}
              </td>
              <td className="py-0.5 text-right tabular-nums text-ink-muted">
                {formatQuantity(point.burdenExact)}
                {point.burdenIsPartial && <span className="ml-1 text-warn">(과소집계)</span>}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

/**
 * What the plot covers and what it had to leave out.
 *
 * An excluded region is NAMED with its reason rather than quietly dropped: a plot
 * that silently omits regions reads as complete coverage of everywhere that matters.
 */
function ScatterCoverage({ dataset, mode }: { dataset: ScatterDataset; mode: BurdenMode }) {
  const grouped = new Map<string, string[]>();
  for (const item of dataset.excluded) {
    const list = grouped.get(item.reason) ?? [];
    list.push(item.regionName);
    grouped.set(item.reason, list);
  }
  return (
    <div className="flex flex-col gap-2 text-[11px] text-ink-muted">
      <dl className="space-y-1">
        <div>
          <dt className="inline font-medium">가로축: </dt>
          <dd className="inline">
            1인당 {SCATTER_STREAM_LABEL} 발생량 · 기준 연도{" "}
            {dataset.generationReferenceYear ?? "—"} ·{" "}
            <DataStatusBadge status="derived" label="공식자료 기반 계산값" />
          </dd>
        </div>
        <div>
          <dt className="inline font-medium">세로축: </dt>
          <dd className="inline">
            1인당 {mode === "buffer" ? "인근" : "지역 내"} 시설 처리량
            {mode === "buffer" && dataset.bufferMeters !== null && (
              <> (반경 {dataset.bufferMeters.toLocaleString("en-US")}m)</>
            )}{" "}
            · 기준 연도 {dataset.burdenReferenceYear ?? "—"} ·{" "}
            <DataStatusBadge status="derived" label="공식자료 기반 계산값" />
          </dd>
        </div>
        <div>
          <dt className="inline font-medium">표시된 지역: </dt>
          <dd className="inline" data-testid="landfill-scatter-count">
            {dataset.points.length}곳
          </dd>
        </div>
      </dl>
      {grouped.size === 0 ? (
        <p>두 지표를 맞출 수 없어 빠진 지역은 없습니다.</p>
      ) : (
        <ul className="list-disc space-y-1 pl-4" data-testid="landfill-scatter-excluded">
          {[...grouped.entries()].map(([reason, names]) => (
            <li key={reason}>
              {SCATTER_EXCLUSION_LABELS[reason as keyof typeof SCATTER_EXCLUSION_LABELS]} (
              {names.length}곳): {names.join(", ")}
              <span className="ml-1" data-diagnostic>
                기술 코드: {reason}
              </span>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
